[2022-09-27 13:11:32,387] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:11:32,401] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:11:32,402] {logging_mixin.py:109} INFO - [2022-09-27 13:11:32,401] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:11:32,405] {logging_mixin.py:109} INFO - [2022-09-27 13:11:32,403] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:11:32,424] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:11:32,438] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.064 seconds
[2022-09-27 13:12:02,536] {processor.py:163} INFO - Started process (PID=57) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:12:02,537] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:12:02,538] {logging_mixin.py:109} INFO - [2022-09-27 13:12:02,537] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:12:02,540] {logging_mixin.py:109} INFO - [2022-09-27 13:12:02,539] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:12:02,560] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:12:02,572] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:12:32,654] {processor.py:163} INFO - Started process (PID=84) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:12:32,659] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:12:32,660] {logging_mixin.py:109} INFO - [2022-09-27 13:12:32,660] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:12:32,664] {logging_mixin.py:109} INFO - [2022-09-27 13:12:32,663] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:12:32,689] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:12:32,701] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:13:02,766] {processor.py:163} INFO - Started process (PID=102) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:13:02,767] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:13:02,768] {logging_mixin.py:109} INFO - [2022-09-27 13:13:02,768] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:13:02,771] {logging_mixin.py:109} INFO - [2022-09-27 13:13:02,770] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:13:02,793] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:13:02,802] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.042 seconds
[2022-09-27 13:13:32,879] {processor.py:163} INFO - Started process (PID=122) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:13:32,882] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:13:32,883] {logging_mixin.py:109} INFO - [2022-09-27 13:13:32,883] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:13:32,887] {logging_mixin.py:109} INFO - [2022-09-27 13:13:32,885] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:13:32,909] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:13:32,924] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 13:14:03,002] {processor.py:163} INFO - Started process (PID=148) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:14:03,004] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:14:03,005] {logging_mixin.py:109} INFO - [2022-09-27 13:14:03,005] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:14:03,009] {logging_mixin.py:109} INFO - [2022-09-27 13:14:03,008] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:14:03,037] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:14:03,050] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.053 seconds
[2022-09-27 13:14:33,115] {processor.py:163} INFO - Started process (PID=169) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:14:33,116] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:14:33,117] {logging_mixin.py:109} INFO - [2022-09-27 13:14:33,117] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:14:33,120] {logging_mixin.py:109} INFO - [2022-09-27 13:14:33,119] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:14:33,142] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:14:33,154] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.044 seconds
[2022-09-27 13:15:03,231] {processor.py:163} INFO - Started process (PID=189) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:15:03,233] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:15:03,235] {logging_mixin.py:109} INFO - [2022-09-27 13:15:03,234] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:15:03,238] {logging_mixin.py:109} INFO - [2022-09-27 13:15:03,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:15:03,268] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:15:03,284] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.059 seconds
[2022-09-27 13:15:33,356] {processor.py:163} INFO - Started process (PID=217) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:15:33,358] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:15:33,359] {logging_mixin.py:109} INFO - [2022-09-27 13:15:33,358] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:15:33,363] {logging_mixin.py:109} INFO - [2022-09-27 13:15:33,361] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:15:33,389] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:15:33,401] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:16:03,468] {processor.py:163} INFO - Started process (PID=236) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:16:03,470] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:16:03,471] {logging_mixin.py:109} INFO - [2022-09-27 13:16:03,471] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:16:03,474] {logging_mixin.py:109} INFO - [2022-09-27 13:16:03,473] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:16:03,495] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:16:03,505] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:16:33,598] {processor.py:163} INFO - Started process (PID=256) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:16:33,600] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:16:33,601] {logging_mixin.py:109} INFO - [2022-09-27 13:16:33,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:16:33,605] {logging_mixin.py:109} INFO - [2022-09-27 13:16:33,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:16:33,629] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:16:33,641] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.048 seconds
[2022-09-27 13:17:03,723] {processor.py:163} INFO - Started process (PID=276) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:17:03,725] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:17:03,726] {logging_mixin.py:109} INFO - [2022-09-27 13:17:03,726] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:17:03,730] {logging_mixin.py:109} INFO - [2022-09-27 13:17:03,729] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:17:03,754] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:17:03,769] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:17:33,842] {processor.py:163} INFO - Started process (PID=305) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:17:33,844] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:17:33,845] {logging_mixin.py:109} INFO - [2022-09-27 13:17:33,845] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:17:33,849] {logging_mixin.py:109} INFO - [2022-09-27 13:17:33,847] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:17:33,872] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:17:33,885] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.048 seconds
[2022-09-27 13:18:03,958] {processor.py:163} INFO - Started process (PID=325) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:18:03,959] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:18:03,960] {logging_mixin.py:109} INFO - [2022-09-27 13:18:03,959] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:18:03,962] {logging_mixin.py:109} INFO - [2022-09-27 13:18:03,962] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:18:03,987] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:18:03,997] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.044 seconds
[2022-09-27 13:18:34,076] {processor.py:163} INFO - Started process (PID=343) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:18:34,082] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:18:34,083] {logging_mixin.py:109} INFO - [2022-09-27 13:18:34,083] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:18:34,087] {logging_mixin.py:109} INFO - [2022-09-27 13:18:34,085] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:18:34,111] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:18:34,124] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.053 seconds
[2022-09-27 13:19:04,192] {processor.py:163} INFO - Started process (PID=372) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:19:04,193] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:19:04,194] {logging_mixin.py:109} INFO - [2022-09-27 13:19:04,194] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:19:04,197] {logging_mixin.py:109} INFO - [2022-09-27 13:19:04,196] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:19:04,217] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:19:04,227] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:19:34,302] {processor.py:163} INFO - Started process (PID=392) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:19:34,305] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:19:34,305] {logging_mixin.py:109} INFO - [2022-09-27 13:19:34,305] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:19:34,309] {logging_mixin.py:109} INFO - [2022-09-27 13:19:34,307] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:19:34,332] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:19:34,344] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:20:04,416] {processor.py:163} INFO - Started process (PID=411) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:20:04,418] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:20:04,419] {logging_mixin.py:109} INFO - [2022-09-27 13:20:04,419] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:20:04,422] {logging_mixin.py:109} INFO - [2022-09-27 13:20:04,421] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:20:04,445] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:20:04,457] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 13:20:34,533] {processor.py:163} INFO - Started process (PID=439) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:20:34,537] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:20:34,537] {logging_mixin.py:109} INFO - [2022-09-27 13:20:34,537] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:20:34,540] {logging_mixin.py:109} INFO - [2022-09-27 13:20:34,539] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:20:34,561] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:20:34,570] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.042 seconds
[2022-09-27 13:21:04,651] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:21:04,653] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:21:04,653] {logging_mixin.py:109} INFO - [2022-09-27 13:21:04,653] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:21:04,656] {logging_mixin.py:109} INFO - [2022-09-27 13:21:04,655] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:21:04,678] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:21:04,688] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:21:34,778] {processor.py:163} INFO - Started process (PID=479) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:21:34,780] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:21:34,781] {logging_mixin.py:109} INFO - [2022-09-27 13:21:34,781] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:21:34,785] {logging_mixin.py:109} INFO - [2022-09-27 13:21:34,784] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:21:34,809] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:21:34,822] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:22:04,890] {processor.py:163} INFO - Started process (PID=507) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:22:04,892] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:22:04,893] {logging_mixin.py:109} INFO - [2022-09-27 13:22:04,892] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:22:04,896] {logging_mixin.py:109} INFO - [2022-09-27 13:22:04,895] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:22:04,922] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:22:04,934] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 13:22:35,001] {processor.py:163} INFO - Started process (PID=526) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:22:35,004] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:22:35,005] {logging_mixin.py:109} INFO - [2022-09-27 13:22:35,005] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:22:35,008] {logging_mixin.py:109} INFO - [2022-09-27 13:22:35,007] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:22:35,028] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:22:35,038] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:23:05,120] {processor.py:163} INFO - Started process (PID=545) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:23:05,121] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:23:05,122] {logging_mixin.py:109} INFO - [2022-09-27 13:23:05,122] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:23:05,126] {logging_mixin.py:109} INFO - [2022-09-27 13:23:05,125] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:23:05,149] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:23:05,158] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.044 seconds
[2022-09-27 13:23:35,234] {processor.py:163} INFO - Started process (PID=570) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:23:35,238] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:23:35,239] {logging_mixin.py:109} INFO - [2022-09-27 13:23:35,238] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:23:35,242] {logging_mixin.py:109} INFO - [2022-09-27 13:23:35,241] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:23:35,268] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:23:35,281] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:24:05,349] {processor.py:163} INFO - Started process (PID=592) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:24:05,351] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:24:05,352] {logging_mixin.py:109} INFO - [2022-09-27 13:24:05,352] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:24:05,355] {logging_mixin.py:109} INFO - [2022-09-27 13:24:05,354] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:24:05,378] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:24:05,390] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:24:35,463] {processor.py:163} INFO - Started process (PID=611) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:24:35,464] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:24:35,465] {logging_mixin.py:109} INFO - [2022-09-27 13:24:35,465] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:24:35,468] {logging_mixin.py:109} INFO - [2022-09-27 13:24:35,467] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:24:35,488] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:24:35,497] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.039 seconds
[2022-09-27 13:25:05,581] {processor.py:163} INFO - Started process (PID=639) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:25:05,584] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:25:05,585] {logging_mixin.py:109} INFO - [2022-09-27 13:25:05,585] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:25:05,590] {logging_mixin.py:109} INFO - [2022-09-27 13:25:05,589] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:25:05,614] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:25:05,627] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:25:35,700] {processor.py:163} INFO - Started process (PID=659) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:25:35,702] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:25:35,703] {logging_mixin.py:109} INFO - [2022-09-27 13:25:35,703] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:25:35,707] {logging_mixin.py:109} INFO - [2022-09-27 13:25:35,706] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:25:35,733] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:25:35,746] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:26:05,813] {processor.py:163} INFO - Started process (PID=677) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:26:05,814] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:26:05,815] {logging_mixin.py:109} INFO - [2022-09-27 13:26:05,815] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:26:05,818] {logging_mixin.py:109} INFO - [2022-09-27 13:26:05,817] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:26:05,838] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:26:05,848] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.039 seconds
[2022-09-27 13:26:35,951] {processor.py:163} INFO - Started process (PID=707) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:26:35,956] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:26:35,957] {logging_mixin.py:109} INFO - [2022-09-27 13:26:35,957] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:26:35,961] {logging_mixin.py:109} INFO - [2022-09-27 13:26:35,960] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:26:36,001] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:26:36,014] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.068 seconds
[2022-09-27 13:27:06,056] {processor.py:163} INFO - Started process (PID=726) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:27:06,058] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:27:06,058] {logging_mixin.py:109} INFO - [2022-09-27 13:27:06,058] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:27:06,061] {logging_mixin.py:109} INFO - [2022-09-27 13:27:06,060] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:27:06,085] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:27:06,099] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:27:36,196] {processor.py:163} INFO - Started process (PID=746) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:27:36,199] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:27:36,199] {logging_mixin.py:109} INFO - [2022-09-27 13:27:36,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:27:36,202] {logging_mixin.py:109} INFO - [2022-09-27 13:27:36,202] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:27:36,227] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:27:36,241] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 13:28:06,308] {processor.py:163} INFO - Started process (PID=764) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:28:06,310] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:28:06,311] {logging_mixin.py:109} INFO - [2022-09-27 13:28:06,311] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:28:06,314] {logging_mixin.py:109} INFO - [2022-09-27 13:28:06,313] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:28:06,337] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:28:06,350] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:28:36,425] {processor.py:163} INFO - Started process (PID=792) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:28:36,427] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:28:36,428] {logging_mixin.py:109} INFO - [2022-09-27 13:28:36,428] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:28:36,432] {logging_mixin.py:109} INFO - [2022-09-27 13:28:36,431] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:28:36,458] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:28:36,471] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:29:06,541] {processor.py:163} INFO - Started process (PID=811) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:29:06,542] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:29:06,543] {logging_mixin.py:109} INFO - [2022-09-27 13:29:06,543] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:29:06,546] {logging_mixin.py:109} INFO - [2022-09-27 13:29:06,545] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:29:06,565] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:29:06,575] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.038 seconds
[2022-09-27 13:29:36,659] {processor.py:163} INFO - Started process (PID=831) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:29:36,661] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:29:36,662] {logging_mixin.py:109} INFO - [2022-09-27 13:29:36,661] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:29:36,665] {logging_mixin.py:109} INFO - [2022-09-27 13:29:36,664] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:29:36,687] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:29:36,701] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 13:30:06,775] {processor.py:163} INFO - Started process (PID=860) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:30:06,777] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:30:06,778] {logging_mixin.py:109} INFO - [2022-09-27 13:30:06,777] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:30:06,781] {logging_mixin.py:109} INFO - [2022-09-27 13:30:06,780] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:30:06,806] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:30:06,822] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:30:36,884] {processor.py:163} INFO - Started process (PID=879) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:30:36,886] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:30:36,887] {logging_mixin.py:109} INFO - [2022-09-27 13:30:36,887] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:30:36,890] {logging_mixin.py:109} INFO - [2022-09-27 13:30:36,889] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:30:36,913] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:30:36,925] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 13:31:07,004] {processor.py:163} INFO - Started process (PID=900) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:31:07,005] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:31:07,006] {logging_mixin.py:109} INFO - [2022-09-27 13:31:07,006] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:31:07,010] {logging_mixin.py:109} INFO - [2022-09-27 13:31:07,009] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:31:07,155] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:31:07,163] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.164 seconds
[2022-09-27 13:31:37,241] {processor.py:163} INFO - Started process (PID=928) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:31:37,244] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:31:37,245] {logging_mixin.py:109} INFO - [2022-09-27 13:31:37,245] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:31:37,250] {logging_mixin.py:109} INFO - [2022-09-27 13:31:37,248] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:31:37,438] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:31:37,449] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.215 seconds
[2022-09-27 13:32:07,529] {processor.py:163} INFO - Started process (PID=947) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:32:07,530] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:32:07,531] {logging_mixin.py:109} INFO - [2022-09-27 13:32:07,531] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:32:07,534] {logging_mixin.py:109} INFO - [2022-09-27 13:32:07,533] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:32:07,557] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:32:07,570] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 13:32:37,635] {processor.py:163} INFO - Started process (PID=966) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:32:37,638] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:32:37,638] {logging_mixin.py:109} INFO - [2022-09-27 13:32:37,638] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:32:37,642] {logging_mixin.py:109} INFO - [2022-09-27 13:32:37,641] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:32:37,664] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:32:37,679] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 13:33:07,756] {processor.py:163} INFO - Started process (PID=992) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:33:07,758] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:33:07,759] {logging_mixin.py:109} INFO - [2022-09-27 13:33:07,759] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:33:07,763] {logging_mixin.py:109} INFO - [2022-09-27 13:33:07,762] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:33:07,789] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:33:07,801] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:33:37,871] {processor.py:163} INFO - Started process (PID=1013) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:33:37,877] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:33:37,878] {logging_mixin.py:109} INFO - [2022-09-27 13:33:37,878] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:33:37,882] {logging_mixin.py:109} INFO - [2022-09-27 13:33:37,881] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:33:37,907] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:33:37,920] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.054 seconds
[2022-09-27 13:34:07,987] {processor.py:163} INFO - Started process (PID=1033) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:34:07,988] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:34:07,989] {logging_mixin.py:109} INFO - [2022-09-27 13:34:07,989] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:34:07,992] {logging_mixin.py:109} INFO - [2022-09-27 13:34:07,991] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:34:08,018] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:34:08,033] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:34:38,103] {processor.py:163} INFO - Started process (PID=1052) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:34:38,107] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:34:38,108] {logging_mixin.py:109} INFO - [2022-09-27 13:34:38,108] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:34:38,111] {logging_mixin.py:109} INFO - [2022-09-27 13:34:38,110] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:34:38,135] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:34:38,147] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 13:35:08,215] {processor.py:163} INFO - Started process (PID=1079) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:35:08,217] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:35:08,217] {logging_mixin.py:109} INFO - [2022-09-27 13:35:08,217] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:35:08,220] {logging_mixin.py:109} INFO - [2022-09-27 13:35:08,219] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:35:08,240] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:35:08,250] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.039 seconds
[2022-09-27 13:35:38,326] {processor.py:163} INFO - Started process (PID=1099) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:35:38,329] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:35:38,330] {logging_mixin.py:109} INFO - [2022-09-27 13:35:38,330] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:35:38,333] {logging_mixin.py:109} INFO - [2022-09-27 13:35:38,332] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:35:38,353] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:35:38,363] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:36:08,440] {processor.py:163} INFO - Started process (PID=1117) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:36:08,441] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:36:08,442] {logging_mixin.py:109} INFO - [2022-09-27 13:36:08,442] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:36:08,446] {logging_mixin.py:109} INFO - [2022-09-27 13:36:08,445] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:36:08,468] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:36:08,484] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 13:36:38,566] {processor.py:163} INFO - Started process (PID=1146) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:36:38,570] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:36:38,571] {logging_mixin.py:109} INFO - [2022-09-27 13:36:38,571] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:36:38,575] {logging_mixin.py:109} INFO - [2022-09-27 13:36:38,573] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:36:38,594] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:36:38,605] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.044 seconds
[2022-09-27 13:37:08,680] {processor.py:163} INFO - Started process (PID=1164) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:37:08,681] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:37:08,682] {logging_mixin.py:109} INFO - [2022-09-27 13:37:08,682] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:37:08,685] {logging_mixin.py:109} INFO - [2022-09-27 13:37:08,684] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:37:08,708] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:37:08,718] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.043 seconds
[2022-09-27 13:37:38,797] {processor.py:163} INFO - Started process (PID=1183) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:37:38,799] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:37:38,800] {logging_mixin.py:109} INFO - [2022-09-27 13:37:38,799] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:37:38,803] {logging_mixin.py:109} INFO - [2022-09-27 13:37:38,802] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:37:38,822] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:37:38,832] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.040 seconds
[2022-09-27 13:38:08,908] {processor.py:163} INFO - Started process (PID=1212) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:38:08,910] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:38:08,910] {logging_mixin.py:109} INFO - [2022-09-27 13:38:08,910] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:38:08,914] {logging_mixin.py:109} INFO - [2022-09-27 13:38:08,913] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:38:08,935] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:38:08,946] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.043 seconds
[2022-09-27 13:38:39,026] {processor.py:163} INFO - Started process (PID=1232) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:38:39,027] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:38:39,028] {logging_mixin.py:109} INFO - [2022-09-27 13:38:39,028] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:38:39,032] {logging_mixin.py:109} INFO - [2022-09-27 13:38:39,031] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:38:39,054] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:38:39,064] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.043 seconds
[2022-09-27 13:39:09,143] {processor.py:163} INFO - Started process (PID=1251) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:39:09,145] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:39:09,147] {logging_mixin.py:109} INFO - [2022-09-27 13:39:09,146] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:39:09,151] {logging_mixin.py:109} INFO - [2022-09-27 13:39:09,149] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:39:09,175] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:39:09,187] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 13:39:39,260] {processor.py:163} INFO - Started process (PID=1281) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:39:39,269] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:39:39,270] {logging_mixin.py:109} INFO - [2022-09-27 13:39:39,270] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:39:39,274] {logging_mixin.py:109} INFO - [2022-09-27 13:39:39,273] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:39:39,301] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:39:39,312] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.057 seconds
[2022-09-27 13:40:09,376] {processor.py:163} INFO - Started process (PID=1300) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:40:09,377] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:40:09,378] {logging_mixin.py:109} INFO - [2022-09-27 13:40:09,378] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:40:09,381] {logging_mixin.py:109} INFO - [2022-09-27 13:40:09,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:40:09,400] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:40:09,410] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.038 seconds
[2022-09-27 13:40:39,487] {processor.py:163} INFO - Started process (PID=1319) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:40:39,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:40:39,490] {logging_mixin.py:109} INFO - [2022-09-27 13:40:39,490] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:40:39,493] {logging_mixin.py:109} INFO - [2022-09-27 13:40:39,492] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:40:39,515] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:40:39,529] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:41:09,610] {processor.py:163} INFO - Started process (PID=1347) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:41:09,611] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:41:09,613] {logging_mixin.py:109} INFO - [2022-09-27 13:41:09,612] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:41:09,617] {logging_mixin.py:109} INFO - [2022-09-27 13:41:09,615] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:41:09,648] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:41:09,665] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.062 seconds
[2022-09-27 13:41:39,748] {processor.py:163} INFO - Started process (PID=1366) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:41:39,750] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:41:39,751] {logging_mixin.py:109} INFO - [2022-09-27 13:41:39,751] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:41:39,754] {logging_mixin.py:109} INFO - [2022-09-27 13:41:39,753] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:41:39,774] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:41:39,784] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:42:09,862] {processor.py:163} INFO - Started process (PID=1385) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:42:09,867] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:42:09,868] {logging_mixin.py:109} INFO - [2022-09-27 13:42:09,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:42:09,873] {logging_mixin.py:109} INFO - [2022-09-27 13:42:09,871] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:42:09,898] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:42:09,911] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.053 seconds
[2022-09-27 13:42:39,983] {processor.py:163} INFO - Started process (PID=1413) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:42:39,988] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:42:39,989] {logging_mixin.py:109} INFO - [2022-09-27 13:42:39,989] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:42:39,994] {logging_mixin.py:109} INFO - [2022-09-27 13:42:39,992] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:42:40,019] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:42:40,032] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.055 seconds
[2022-09-27 13:43:10,092] {processor.py:163} INFO - Started process (PID=1432) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:43:10,094] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:43:10,095] {logging_mixin.py:109} INFO - [2022-09-27 13:43:10,095] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:43:10,098] {logging_mixin.py:109} INFO - [2022-09-27 13:43:10,097] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:43:10,120] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:43:10,133] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 13:43:40,209] {processor.py:163} INFO - Started process (PID=1451) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:43:40,211] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:43:40,211] {logging_mixin.py:109} INFO - [2022-09-27 13:43:40,211] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:43:40,215] {logging_mixin.py:109} INFO - [2022-09-27 13:43:40,214] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:43:40,238] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:43:40,252] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.048 seconds
[2022-09-27 13:44:10,333] {processor.py:163} INFO - Started process (PID=1479) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:44:10,336] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:44:10,337] {logging_mixin.py:109} INFO - [2022-09-27 13:44:10,337] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:44:10,341] {logging_mixin.py:109} INFO - [2022-09-27 13:44:10,339] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:44:10,367] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:44:10,380] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:44:40,435] {processor.py:163} INFO - Started process (PID=1500) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:44:40,437] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:44:40,438] {logging_mixin.py:109} INFO - [2022-09-27 13:44:40,437] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:44:40,441] {logging_mixin.py:109} INFO - [2022-09-27 13:44:40,440] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:44:40,460] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:44:40,470] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.040 seconds
[2022-09-27 13:45:10,550] {processor.py:163} INFO - Started process (PID=1519) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:45:10,552] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:45:10,553] {logging_mixin.py:109} INFO - [2022-09-27 13:45:10,553] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:45:10,558] {logging_mixin.py:109} INFO - [2022-09-27 13:45:10,557] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:45:10,585] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:45:10,596] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:45:40,664] {processor.py:163} INFO - Started process (PID=1539) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:45:40,666] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:45:40,667] {logging_mixin.py:109} INFO - [2022-09-27 13:45:40,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:45:40,671] {logging_mixin.py:109} INFO - [2022-09-27 13:45:40,670] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:45:40,694] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:45:40,705] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:46:10,781] {processor.py:163} INFO - Started process (PID=1567) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:46:10,783] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:46:10,784] {logging_mixin.py:109} INFO - [2022-09-27 13:46:10,784] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:46:10,788] {logging_mixin.py:109} INFO - [2022-09-27 13:46:10,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:46:10,816] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:46:10,829] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.053 seconds
[2022-09-27 13:46:40,902] {processor.py:163} INFO - Started process (PID=1586) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:46:40,904] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:46:40,905] {logging_mixin.py:109} INFO - [2022-09-27 13:46:40,905] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:46:40,908] {logging_mixin.py:109} INFO - [2022-09-27 13:46:40,907] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:46:40,932] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:46:40,945] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.048 seconds
[2022-09-27 13:47:11,021] {processor.py:163} INFO - Started process (PID=1605) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:47:11,022] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:47:11,023] {logging_mixin.py:109} INFO - [2022-09-27 13:47:11,023] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:47:11,026] {logging_mixin.py:109} INFO - [2022-09-27 13:47:11,025] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:47:11,047] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:47:11,058] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:47:41,133] {processor.py:163} INFO - Started process (PID=1633) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:47:41,135] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:47:41,136] {logging_mixin.py:109} INFO - [2022-09-27 13:47:41,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:47:41,140] {logging_mixin.py:109} INFO - [2022-09-27 13:47:41,138] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:47:41,165] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:47:41,177] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 13:48:11,243] {processor.py:163} INFO - Started process (PID=1653) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:48:11,247] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:48:11,248] {logging_mixin.py:109} INFO - [2022-09-27 13:48:11,248] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:48:11,252] {logging_mixin.py:109} INFO - [2022-09-27 13:48:11,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:48:11,275] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:48:11,285] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:48:41,362] {processor.py:163} INFO - Started process (PID=1673) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:48:41,363] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:48:41,364] {logging_mixin.py:109} INFO - [2022-09-27 13:48:41,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:48:41,367] {logging_mixin.py:109} INFO - [2022-09-27 13:48:41,366] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:48:41,388] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:48:41,399] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.042 seconds
[2022-09-27 13:49:11,521] {processor.py:163} INFO - Started process (PID=1702) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:49:11,523] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:49:11,525] {logging_mixin.py:109} INFO - [2022-09-27 13:49:11,525] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:49:11,529] {logging_mixin.py:109} INFO - [2022-09-27 13:49:11,528] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:49:11,560] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:49:11,573] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.058 seconds
[2022-09-27 13:49:41,625] {processor.py:163} INFO - Started process (PID=1721) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:49:41,627] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:49:41,628] {logging_mixin.py:109} INFO - [2022-09-27 13:49:41,628] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:49:41,631] {logging_mixin.py:109} INFO - [2022-09-27 13:49:41,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:49:41,651] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:49:41,661] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.040 seconds
[2022-09-27 13:50:11,753] {processor.py:163} INFO - Started process (PID=1740) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:50:11,755] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:50:11,756] {logging_mixin.py:109} INFO - [2022-09-27 13:50:11,756] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:50:11,760] {logging_mixin.py:109} INFO - [2022-09-27 13:50:11,759] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:50:11,786] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:50:11,798] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:50:41,868] {processor.py:163} INFO - Started process (PID=1759) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:50:41,870] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:50:41,871] {logging_mixin.py:109} INFO - [2022-09-27 13:50:41,870] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:50:41,874] {logging_mixin.py:109} INFO - [2022-09-27 13:50:41,873] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:50:41,899] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:50:41,911] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.048 seconds
[2022-09-27 13:51:11,991] {processor.py:163} INFO - Started process (PID=1787) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:51:11,997] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:51:11,999] {logging_mixin.py:109} INFO - [2022-09-27 13:51:11,998] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:51:12,003] {logging_mixin.py:109} INFO - [2022-09-27 13:51:12,001] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:51:12,027] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:51:12,040] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.054 seconds
[2022-09-27 13:51:42,111] {processor.py:163} INFO - Started process (PID=1807) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:51:42,113] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:51:42,114] {logging_mixin.py:109} INFO - [2022-09-27 13:51:42,114] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:51:42,117] {logging_mixin.py:109} INFO - [2022-09-27 13:51:42,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:51:42,137] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:51:42,147] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:52:12,227] {processor.py:163} INFO - Started process (PID=1825) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:52:12,229] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:52:12,230] {logging_mixin.py:109} INFO - [2022-09-27 13:52:12,230] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:52:12,233] {logging_mixin.py:109} INFO - [2022-09-27 13:52:12,232] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:52:12,256] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:52:12,267] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.045 seconds
[2022-09-27 13:52:42,367] {processor.py:163} INFO - Started process (PID=1854) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:52:42,369] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:52:42,370] {logging_mixin.py:109} INFO - [2022-09-27 13:52:42,370] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:52:42,374] {logging_mixin.py:109} INFO - [2022-09-27 13:52:42,373] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:52:42,399] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:52:42,412] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 13:53:12,479] {processor.py:163} INFO - Started process (PID=1874) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:53:12,482] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:53:12,483] {logging_mixin.py:109} INFO - [2022-09-27 13:53:12,482] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:53:12,486] {logging_mixin.py:109} INFO - [2022-09-27 13:53:12,485] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:53:12,510] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:53:12,522] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.048 seconds
[2022-09-27 13:53:42,601] {processor.py:163} INFO - Started process (PID=1893) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:53:42,603] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:53:42,604] {logging_mixin.py:109} INFO - [2022-09-27 13:53:42,604] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:53:42,607] {logging_mixin.py:109} INFO - [2022-09-27 13:53:42,606] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:53:42,627] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:53:42,637] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.042 seconds
[2022-09-27 13:54:12,721] {processor.py:163} INFO - Started process (PID=1912) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:54:12,724] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:54:12,725] {logging_mixin.py:109} INFO - [2022-09-27 13:54:12,724] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:54:12,728] {logging_mixin.py:109} INFO - [2022-09-27 13:54:12,727] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:54:12,753] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:54:12,767] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.051 seconds
[2022-09-27 13:54:42,841] {processor.py:163} INFO - Started process (PID=1940) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:54:42,845] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:54:42,845] {logging_mixin.py:109} INFO - [2022-09-27 13:54:42,845] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:54:42,848] {logging_mixin.py:109} INFO - [2022-09-27 13:54:42,847] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:54:42,867] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:54:42,877] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:55:12,960] {processor.py:163} INFO - Started process (PID=1959) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:55:12,961] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:55:12,962] {logging_mixin.py:109} INFO - [2022-09-27 13:55:12,962] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:55:12,966] {logging_mixin.py:109} INFO - [2022-09-27 13:55:12,965] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:55:12,989] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:55:13,001] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:55:43,079] {processor.py:163} INFO - Started process (PID=1977) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:55:43,081] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:55:43,082] {logging_mixin.py:109} INFO - [2022-09-27 13:55:43,082] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:55:43,085] {logging_mixin.py:109} INFO - [2022-09-27 13:55:43,084] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:55:43,105] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:55:43,116] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.042 seconds
[2022-09-27 13:56:13,190] {processor.py:163} INFO - Started process (PID=2006) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:56:13,192] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:56:13,193] {logging_mixin.py:109} INFO - [2022-09-27 13:56:13,193] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:56:13,196] {logging_mixin.py:109} INFO - [2022-09-27 13:56:13,195] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:56:13,218] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:56:13,227] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.042 seconds
[2022-09-27 13:56:43,315] {processor.py:163} INFO - Started process (PID=2026) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:56:43,319] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:56:43,320] {logging_mixin.py:109} INFO - [2022-09-27 13:56:43,320] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:56:43,324] {logging_mixin.py:109} INFO - [2022-09-27 13:56:43,323] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:56:43,346] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:56:43,359] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 13:57:13,428] {processor.py:163} INFO - Started process (PID=2046) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:57:13,431] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:57:13,431] {logging_mixin.py:109} INFO - [2022-09-27 13:57:13,431] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:57:13,435] {logging_mixin.py:109} INFO - [2022-09-27 13:57:13,434] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:57:13,458] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:57:13,469] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 13:57:43,557] {processor.py:163} INFO - Started process (PID=2075) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:57:43,559] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:57:43,560] {logging_mixin.py:109} INFO - [2022-09-27 13:57:43,560] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:57:43,564] {logging_mixin.py:109} INFO - [2022-09-27 13:57:43,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:57:43,590] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:57:43,602] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 13:58:13,669] {processor.py:163} INFO - Started process (PID=2095) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:58:13,672] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:58:13,672] {logging_mixin.py:109} INFO - [2022-09-27 13:58:13,672] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:58:13,675] {logging_mixin.py:109} INFO - [2022-09-27 13:58:13,674] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:58:13,696] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:58:13,706] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 13:58:43,783] {processor.py:163} INFO - Started process (PID=2115) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:58:43,784] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:58:43,785] {logging_mixin.py:109} INFO - [2022-09-27 13:58:43,785] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:58:43,788] {logging_mixin.py:109} INFO - [2022-09-27 13:58:43,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:58:43,811] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:58:43,820] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.043 seconds
[2022-09-27 13:59:13,900] {processor.py:163} INFO - Started process (PID=2125) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:59:13,908] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:59:13,909] {logging_mixin.py:109} INFO - [2022-09-27 13:59:13,909] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:59:13,912] {logging_mixin.py:109} INFO - [2022-09-27 13:59:13,911] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 13:59:13,936] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:59:13,949] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.056 seconds
[2022-09-27 13:59:44,012] {processor.py:163} INFO - Started process (PID=2126) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:59:44,014] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 13:59:44,014] {logging_mixin.py:109} INFO - [2022-09-27 13:59:44,014] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 13:59:44,017] {logging_mixin.py:109} INFO - [2022-09-27 13:59:44,016] {dagbag.py:334} ERROR - Fail[2022-09-27 14:00:14,369] {processor.py:163} INFO - Started process (PID=2136) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:00:14,372] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:00:14,373] {logging_mixin.py:109} INFO - [2022-09-27 14:00:14,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:00:14,383] {logging_mixin.py:109} INFO - [2022-09-27 14:00:14,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:00:14,418] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:00:14,434] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.073 seconds
[2022-09-27 14:00:44,475] {processor.py:163} INFO - Started process (PID=2165) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:00:44,476] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:00:44,477] {logging_mixin.py:109} INFO - [2022-09-27 14:00:44,477] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:00:44,481] {logging_mixin.py:109} INFO - [2022-09-27 14:00:44,480] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:00:44,518] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:00:44,533] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.064 seconds
[2022-09-27 14:01:14,628] {processor.py:163} INFO - Started process (PID=2183) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:01:14,632] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:01:14,633] {logging_mixin.py:109} INFO - [2022-09-27 14:01:14,633] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:01:14,637] {logging_mixin.py:109} INFO - [2022-09-27 14:01:14,636] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:01:14,663] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:01:14,675] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.053 seconds
[2022-09-27 14:01:44,760] {processor.py:163} INFO - Started process (PID=2202) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:01:44,766] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:01:44,767] {logging_mixin.py:109} INFO - [2022-09-27 14:01:44,767] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:01:44,771] {logging_mixin.py:109} INFO - [2022-09-27 14:01:44,770] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:01:44,799] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:01:44,817] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.063 seconds
[2022-09-27 14:02:14,871] {processor.py:163} INFO - Started process (PID=2228) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:02:14,873] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:02:14,874] {logging_mixin.py:109} INFO - [2022-09-27 14:02:14,874] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:02:14,878] {logging_mixin.py:109} INFO - [2022-09-27 14:02:14,877] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:02:14,901] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:02:14,912] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 14:02:45,002] {processor.py:163} INFO - Started process (PID=2248) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:02:45,005] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:02:45,006] {logging_mixin.py:109} INFO - [2022-09-27 14:02:45,006] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:02:45,009] {logging_mixin.py:109} INFO - [2022-09-27 14:02:45,008] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:02:45,032] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:02:45,046] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 14:03:15,122] {processor.py:163} INFO - Started process (PID=2268) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:03:15,123] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:03:15,124] {logging_mixin.py:109} INFO - [2022-09-27 14:03:15,124] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:03:15,127] {logging_mixin.py:109} INFO - [2022-09-27 14:03:15,126] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:03:15,149] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:03:15,160] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.043 seconds
[2022-09-27 14:03:45,245] {processor.py:163} INFO - Started process (PID=2297) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:03:45,248] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:03:45,249] {logging_mixin.py:109} INFO - [2022-09-27 14:03:45,249] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:03:45,252] {logging_mixin.py:109} INFO - [2022-09-27 14:03:45,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:03:45,277] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:03:45,289] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 14:04:15,358] {processor.py:163} INFO - Started process (PID=2317) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:04:15,362] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:04:15,364] {logging_mixin.py:109} INFO - [2022-09-27 14:04:15,363] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:04:15,367] {logging_mixin.py:109} INFO - [2022-09-27 14:04:15,366] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:04:15,390] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:04:15,401] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 14:04:45,482] {processor.py:163} INFO - Started process (PID=2337) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:04:45,484] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:04:45,485] {logging_mixin.py:109} INFO - [2022-09-27 14:04:45,485] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:04:45,489] {logging_mixin.py:109} INFO - [2022-09-27 14:04:45,487] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:04:45,512] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:04:45,524] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 14:05:15,594] {processor.py:163} INFO - Started process (PID=2356) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:05:15,596] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:05:15,597] {logging_mixin.py:109} INFO - [2022-09-27 14:05:15,597] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:05:15,601] {logging_mixin.py:109} INFO - [2022-09-27 14:05:15,600] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:05:15,624] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:05:15,635] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 14:05:45,707] {processor.py:163} INFO - Started process (PID=2386) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:05:45,713] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:05:45,714] {logging_mixin.py:109} INFO - [2022-09-27 14:05:45,714] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:05:45,717] {logging_mixin.py:109} INFO - [2022-09-27 14:05:45,716] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:05:45,736] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:05:45,749] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 14:06:15,819] {processor.py:163} INFO - Started process (PID=2405) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:06:15,824] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:06:15,825] {logging_mixin.py:109} INFO - [2022-09-27 14:06:15,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:06:15,827] {logging_mixin.py:109} INFO - [2022-09-27 14:06:15,827] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:06:15,850] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:06:15,863] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.049 seconds
[2022-09-27 14:06:46,027] {processor.py:163} INFO - Started process (PID=2424) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:06:46,030] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:06:46,034] {logging_mixin.py:109} INFO - [2022-09-27 14:06:46,034] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:06:46,046] {logging_mixin.py:109} INFO - [2022-09-27 14:06:46,042] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:06:46,113] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:06:46,137] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.128 seconds
[2022-09-27 14:07:16,198] {processor.py:163} INFO - Started process (PID=2442) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:07:16,204] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:07:16,205] {logging_mixin.py:109} INFO - [2022-09-27 14:07:16,205] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:07:16,210] {logging_mixin.py:109} INFO - [2022-09-27 14:07:16,209] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:07:16,247] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:07:16,262] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.072 seconds
[2022-09-27 14:07:46,349] {processor.py:163} INFO - Started process (PID=2462) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:07:46,352] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:07:46,353] {logging_mixin.py:109} INFO - [2022-09-27 14:07:46,353] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:07:46,357] {logging_mixin.py:109} INFO - [2022-09-27 14:07:46,356] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:07:46,389] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:07:46,401] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.059 seconds
[2022-09-27 14:08:16,466] {processor.py:163} INFO - Started process (PID=2490) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:08:16,467] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:08:16,468] {logging_mixin.py:109} INFO - [2022-09-27 14:08:16,468] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:08:16,471] {logging_mixin.py:109} INFO - [2022-09-27 14:08:16,470] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:08:16,492] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:08:16,501] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.041 seconds
[2022-09-27 14:08:46,594] {processor.py:163} INFO - Started process (PID=2511) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:08:46,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:08:46,598] {logging_mixin.py:109} INFO - [2022-09-27 14:08:46,598] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:08:46,602] {logging_mixin.py:109} INFO - [2022-09-27 14:08:46,601] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:08:46,631] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:08:46,644] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.055 seconds
[2022-09-27 14:09:16,708] {processor.py:163} INFO - Started process (PID=2529) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:09:16,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:09:16,710] {logging_mixin.py:109} INFO - [2022-09-27 14:09:16,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:09:16,713] {logging_mixin.py:109} INFO - [2022-09-27 14:09:16,712] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:09:16,737] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:09:16,749] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 14:09:46,857] {processor.py:163} INFO - Started process (PID=2559) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:09:46,866] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:09:46,867] {logging_mixin.py:109} INFO - [2022-09-27 14:09:46,867] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:09:46,871] {logging_mixin.py:109} INFO - [2022-09-27 14:09:46,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:09:46,915] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:09:46,939] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.087 seconds
[2022-09-27 14:10:16,985] {processor.py:163} INFO - Started process (PID=2578) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:10:16,988] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:10:16,989] {logging_mixin.py:109} INFO - [2022-09-27 14:10:16,989] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:10:16,992] {logging_mixin.py:109} INFO - [2022-09-27 14:10:16,991] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:10:17,014] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:10:17,024] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.044 seconds
[2022-09-27 14:10:47,120] {processor.py:163} INFO - Started process (PID=2596) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:10:47,121] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:10:47,122] {logging_mixin.py:109} INFO - [2022-09-27 14:10:47,122] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:10:47,125] {logging_mixin.py:109} INFO - [2022-09-27 14:10:47,124] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:10:47,145] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:10:47,154] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.039 seconds
[2022-09-27 14:11:17,238] {processor.py:163} INFO - Started process (PID=2615) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:11:17,241] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:11:17,241] {logging_mixin.py:109} INFO - [2022-09-27 14:11:17,241] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:11:17,244] {logging_mixin.py:109} INFO - [2022-09-27 14:11:17,244] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:11:17,268] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:11:17,281] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.047 seconds
[2022-09-27 14:11:47,382] {processor.py:163} INFO - Started process (PID=2643) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:11:47,383] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:11:47,384] {logging_mixin.py:109} INFO - [2022-09-27 14:11:47,384] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:11:47,388] {logging_mixin.py:109} INFO - [2022-09-27 14:11:47,387] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:11:47,415] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:11:47,428] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 14:12:17,501] {processor.py:163} INFO - Started process (PID=2663) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:12:17,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:12:17,504] {logging_mixin.py:109} INFO - [2022-09-27 14:12:17,504] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:12:17,508] {logging_mixin.py:109} INFO - [2022-09-27 14:12:17,507] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:12:17,531] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:12:17,541] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 14:12:47,625] {processor.py:163} INFO - Started process (PID=2683) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:12:47,627] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:12:47,628] {logging_mixin.py:109} INFO - [2022-09-27 14:12:47,628] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:12:47,631] {logging_mixin.py:109} INFO - [2022-09-27 14:12:47,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:12:47,657] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:12:47,670] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.050 seconds
[2022-09-27 14:13:17,745] {processor.py:163} INFO - Started process (PID=2713) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:13:17,747] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:13:17,748] {logging_mixin.py:109} INFO - [2022-09-27 14:13:17,748] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:13:17,752] {logging_mixin.py:109} INFO - [2022-09-27 14:13:17,751] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:13:17,778] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:13:17,790] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.052 seconds
[2022-09-27 14:13:47,862] {processor.py:163} INFO - Started process (PID=2732) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:13:47,864] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:13:47,865] {logging_mixin.py:109} INFO - [2022-09-27 14:13:47,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:13:47,869] {logging_mixin.py:109} INFO - [2022-09-27 14:13:47,868] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:13:47,892] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:13:47,903] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.046 seconds
[2022-09-27 14:14:17,986] {processor.py:163} INFO - Started process (PID=2751) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:14:17,988] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:14:17,989] {logging_mixin.py:109} INFO - [2022-09-27 14:14:17,989] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:14:17,992] {logging_mixin.py:109} INFO - [2022-09-27 14:14:17,991] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:14:18,037] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:14:18,053] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.072 seconds
[2022-09-27 14:14:48,106] {processor.py:163} INFO - Started process (PID=2779) to work on /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:14:48,114] {processor.py:642} INFO - Processing file /opt/airflow/dags/kag_to_gcs_dag.py for tasks to queue
[2022-09-27 14:14:48,115] {logging_mixin.py:109} INFO - [2022-09-27 14:14:48,115] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:14:48,119] {logging_mixin.py:109} INFO - [2022-09-27 14:14:48,118] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/kag_to_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/kag_to_gcs_dag.py", line 112
    )
    ^
SyntaxError: invalid syntax
[2022-09-27 14:14:48,144] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/kag_to_gcs_dag.py
[2022-09-27 14:14:48,156] {processor.py:171} INFO - Processing /opt/airflow/dags/kag_to_gcs_dag.py took 0.055 seconds
